REBELinBLUE/deployer

resources/views/dialogs/key.blade.php

Just a small thing, super quick fix

Fixed HTML being escaped in ssh key Dialog. 

---

.gitignore
app/Commands/DeployProject.php
app/Http/Controllers/NotificationController.php
app/Http/Requests/StoreServerRequest.php
app/Notification.php

Issue #6 fixed

---

app/Bootstrap/ConfigureLogging.php
app/Console/Kernel.php
app/Http/Kernel.php

#39 fixed by add a custom logging bootstrap class.

#39 fixed, referenced the way from my another project's logging.

---

.gitignore
app/CheckUrl.php
app/Commands/RequestProjectCheckUrl.php
app/Console/Commands/CheckUrl.php
app/Console/Kernel.php
app/Handlers/Events/Notify.php
app/Http/Controllers/CheckUrlController.php
app/Http/Controllers/DeploymentController.php
app/Http/Requests/StoreCheckUrlRequest.php
app/Http/routes.php
app/Project.php
app/ProjectRelationModel.php
app/Providers/RouteServiceProvider.php
database/migrations/2015_05_27_234354_create_url_checks_table.php
gulpfile.js
resources/assets/js/checkUrls.js
resources/lang/en/checkUrls.php
resources/lang/en/deployments.php
resources/views/dialogs/check_urls.blade.php
resources/views/projects/_partials/check_urls.blade.php
resources/views/projects/details.blade.php

Reverts REBELinBLUE/deployer#45

Revert "Revert "Issue #11 fixed""

---

resources/views/dialogs/check_urls.blade.php
supervisor.conf.example

Change the queue:listen to queue:work to process jobs.

Fix #51 issue

---

app/Console/Commands/CheckHeartbeats.php
app/Http/Requests/StoreNotificationRequest.php
app/Jobs/QueueDeployment.php
app/Jobs/RequestProjectCheckUrl.php
app/Notification.php

Remove Queue::push by $this->dispatch(), convert the active_url with url rule.

Remove Queue::push use and fix active_url rule failed.

---

app/Http/Requests/StoreCheckUrlRequest.php
app/Presenters/ProjectPresenter.php
app/Project.php
resources/views/projects/details.blade.php

These commit also change the check url's validate rule from "active_url" to "url".
Tips:
@REBELinBLUE  I use the sublime.phpfmt plugin to format the php code. You can try it.

Update the application status view simply like below

---

app/Jobs/DeployProject.php

Also removed the unused Config and App\Events\DeploymentStatusChanged

Set access right to 664 for the project global file

---

resources/assets/css/app.css
resources/lang/en/projectFiles.php
resources/views/projects/details.blade.php

Fix for the layout like below because of the char out is too much.

Fix the navtab overflow

---

app/Http/Controllers/Auth/AuthController.php

Default to remember the user login

---

.env.example
.gitignore
Vagrantfile
app/Console/Commands/Install.php
app/Console/Commands/InstallApp.php
app/Console/Commands/ResetApp.php
app/Console/Commands/UpdateApp.php
app/Console/Kernel.php
composer.json
composer.lock
database/migrations/2014_10_12_000000_create_users_table.php
database/seeds/UserTableSeeder.php
phpci.yml

This creates an installer to allow setup to be done with `php artisan app:install` and updating with `php artisan app:update`

Creating an installer

---

README.md

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.
_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._
---
*Please provide a description of the change here.*
2 more steps were to requierd complete the setup

[IMPROVEMENT] Added HTTP and Node instructions to Install section

---

resources/views/commands/dialog.blade.php

**In raising this pull request, I confirm the following:**
- [ X ] I have read and understood the [contributing guidelines](/.github/CONTRIBUTING.md)?
- [ X ] I have checked that another pull request for this purpose does not exist.
- [ X ] I have considered, and confirmed that this submission will be valuable to others.
- [ X ] Do the PHPCI tests pass?
- [ X ] Does the StyleCI test pass?
---
There were typos at descriptions of:
{{ deployer_email }}
{{ deployer_name }}
{{ committer_email }}
{{ committer_name }}

**[FIX]** Incorrect Lang variables

---

resources/assets/js/Components/Box.jsx
resources/assets/js/Components/Projects.jsx
resources/assets/js/Components/Timeline.jsx

---
I've added a very simple Box component to save repeating the same HTML structures in multiple places.

Box component

---

app/Command.php
app/ProjectFile.php
app/SharedFile.php
app/Traits/HasTarget.php
app/Variable.php

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.
_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._
---
*Please provide a description of the change here.*

Added target trait

---

app/Contracts/Repositories/DeploymentRepositoryInterface.php
app/Http/Controllers/DeploymentController.php
app/Repositories/EloquentDeploymentRepository.php

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.
_NOTE: The last 2 are not required to open a PR and can be done afterwards /
while the PR is open._
---
*Please provide a description of the change here.*

Fixed missing reason of rollback

---

.env.example
config/queue.php

Allow the beanstalkd port to be supplied

---

examples/nginx.conf

Please prefix your pull request with one of the following: **[FEATURE]** **[FIX]** **[IMPROVEMENT]**.
---
See https://github.com/REBELinBLUE/deployer/issues/299 .

[IMPROVEMENT] Add a little reminder about SSL server names in nginx upstreams

---

examples/nginx.conf

---
Add comment in nginx example about websockets and https

 [IMPROVEMENT] Update nginx.conf

---

Makefile

Changed the `Makefile` slightly 😄 
Added `make help` (as default for `make` too) and some simple docs for each target

Add quick help target to make

---

.github/PULL_REQUEST_TEMPLATE.md

Fix permanent link to your CONTRIBUTING.md

---

tests/Unit/DeploymentTest.php

---
Improve how the project relationship is set.

[IMPROVEMENT] Update Deployment Test
